apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: service
metadata:
  name: svc-nginx
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector: 
    app: nginx
  type: LoadBalancer
  
